import {
  expandTimetableRecurrence,
  isoDateInTimeZone,
  planningManagement,
  zonedDateTimeToDate,
  type IsoWeekday,
} from "@avermate/core/planning";
import { and, asc, eq, inArray } from "drizzle-orm";
import { z } from "zod";
import { db } from "../../db";
import { timetableOccurrences, timetableSeries } from "../../db/schema";
import { assertSameYear } from "../../lib/domain-integrity";
import { badRequest, protectedProcedure } from "../../lib/orpc";
import {
  assertActive,
  assertEditablePatch,
  assertManaged,
  dateOnlySchema,
  idSchema,
  localNoteSchema,
  loadPlanningConnectionInfo,
  optionalTextSchema,
  publicOccurrence,
  publicSeries,
  requireTimetableOccurrence,
  requireTimetableSeries,
  timezoneSchema,
  titleSchema,
  validatePlanningScope,
} from "./shared";

const weekdaySchema = z.number().int().min(1).max(7);
const recurrenceSchema = z.object({
  frequency: z.enum(["daily", "weekly"]),
  interval: z.number().int().min(1).max(52).default(1),
  weekdays: z.array(weekdaySchema).max(7).default([]),
});

const seriesFields = {
  title: titleSchema,
  notes: optionalTextSchema,
  localNote: localNoteSchema,
  startsOn: dateOnlySchema,
  endsOn: dateOnlySchema.nullable(),
  startMinutes: z.number().int().min(0).max(1_439),
  durationMinutes: z.number().int().min(1).max(1_440),
  timezone: timezoneSchema,
  recurrence: recurrenceSchema,
  location: z.string().trim().max(300).nullable(),
  subjectId: idSchema.nullable(),
};

const createSeriesInput = z
  .object({
    yearId: idSchema,
    title: seriesFields.title,
    notes: seriesFields.notes.default(null),
    localNote: seriesFields.localNote.default(null),
    startsOn: seriesFields.startsOn,
    endsOn: seriesFields.endsOn.default(null),
    startMinutes: seriesFields.startMinutes,
    durationMinutes: seriesFields.durationMinutes,
    timezone: seriesFields.timezone.default("UTC"),
    recurrence: seriesFields.recurrence,
    location: seriesFields.location.default(null),
    subjectId: seriesFields.subjectId.default(null),
  })
  .refine((input) => !input.endsOn || input.endsOn >= input.startsOn, {
    message: "The timetable series cannot end before it starts",
  });

const updateSeriesInput = z
  .object({
    seriesId: idSchema,
    title: seriesFields.title.optional(),
    notes: seriesFields.notes.optional(),
    localNote: seriesFields.localNote.optional(),
    startsOn: seriesFields.startsOn.optional(),
    endsOn: seriesFields.endsOn.optional(),
    startMinutes: seriesFields.startMinutes.optional(),
    durationMinutes: seriesFields.durationMinutes.optional(),
    timezone: seriesFields.timezone.optional(),
    recurrence: seriesFields.recurrence.optional(),
    location: seriesFields.location.optional(),
    subjectId: seriesFields.subjectId.optional(),
  })
  .refine(
    ({ seriesId: _seriesId, ...patch }) =>
      Object.values(patch).some((value) => value !== undefined),
    "At least one timetable series field must change",
  );

function seriesRule(row: typeof timetableSeries.$inferSelect) {
  return {
    frequency: row.recurrenceFrequency,
    interval: row.recurrenceInterval,
    weekdays: row.recurrenceWeekdays,
    startsOn: row.startsOn,
    endsOn: row.endsOn,
  };
}

function baseOccurrence(
  row: typeof timetableSeries.$inferSelect,
  date: string,
) {
  if (expandTimetableRecurrence(seriesRule(row), date, date).length === 0) {
    badRequest("That date is not generated by the timetable series");
  }
  const startsAt = zonedDateTimeToDate(date, row.startMinutes, row.timezone);
  return {
    seriesId: row.id,
    occurrenceDate: date,
    title: row.title,
    notes: row.notes,
    localNote: row.localNote,
    startsAt,
    endsAt: new Date(startsAt.getTime() + row.durationMinutes * 60_000),
    timezone: row.timezone,
    status: "scheduled" as const,
    isException: true,
    location: row.location,
    subjectId: row.subjectId,
    yearId: row.yearId,
    userId: row.userId,
    sourceConnectionId: row.sourceConnectionId,
    externalId:
      row.externalId && row.sourceConnectionId
        ? `${row.externalId}#${date}`
        : null,
    syncState: row.syncState,
  };
}

const standaloneOccurrenceInput = z.object({
  yearId: idSchema,
  seriesId: z.null().default(null),
  occurrenceDate: dateOnlySchema,
  title: titleSchema,
  notes: optionalTextSchema.default(null),
  localNote: localNoteSchema.default(null),
  startsAt: z.coerce.date(),
  endsAt: z.coerce.date(),
  timezone: timezoneSchema.default("UTC"),
  location: z.string().trim().max(300).nullable().default(null),
  subjectId: idSchema.nullable().default(null),
});

const seriesOccurrenceInput = z.object({
  seriesId: idSchema,
  occurrenceDate: dateOnlySchema,
  title: titleSchema.optional(),
  notes: optionalTextSchema.optional(),
  localNote: localNoteSchema.optional(),
  startsAt: z.coerce.date().optional(),
  endsAt: z.coerce.date().optional(),
  timezone: timezoneSchema.optional(),
  location: z.string().trim().max(300).nullable().optional(),
  subjectId: idSchema.nullable().optional(),
});

const createOccurrenceInput = z.union([
  standaloneOccurrenceInput,
  seriesOccurrenceInput,
]);

const updateOccurrenceInput = z
  .object({
    occurrenceId: idSchema,
    title: titleSchema.optional(),
    notes: optionalTextSchema.optional(),
    localNote: localNoteSchema.optional(),
    startsAt: z.coerce.date().optional(),
    endsAt: z.coerce.date().optional(),
    timezone: timezoneSchema.optional(),
    location: z.string().trim().max(300).nullable().optional(),
    subjectId: idSchema.nullable().optional(),
  })
  .refine(
    ({ occurrenceId: _occurrenceId, ...patch }) =>
      Object.values(patch).some((value) => value !== undefined),
    "At least one timetable occurrence field must change",
  );

const occurrenceLocator = z.union([
  z.object({ occurrenceId: idSchema }),
  z.object({ seriesId: idSchema, occurrenceDate: dateOnlySchema }),
]);

async function resolveOrMaterialize(
  userId: string,
  locator: z.infer<typeof occurrenceLocator>,
) {
  if ("occurrenceId" in locator) {
    return requireTimetableOccurrence(userId, locator.occurrenceId);
  }
  const series = await requireTimetableSeries(userId, locator.seriesId);
  assertActive(series, "Timetable series");
  const [existing] = await db
    .select()
    .from(timetableOccurrences)
    .where(
      and(
        eq(timetableOccurrences.userId, userId),
        eq(timetableOccurrences.seriesId, series.id),
        eq(timetableOccurrences.occurrenceDate, locator.occurrenceDate),
      ),
    )
    .limit(1);
  if (existing) return existing;
  const [created] = await db
    .insert(timetableOccurrences)
    .values(baseOccurrence(series, locator.occurrenceDate))
    .returning();
  return created!;
}

export const planningTimetableRouter = {
  listSeries: protectedProcedure
    .input(
      z.object({
        yearId: idSchema,
        includeMissing: z.boolean().default(false),
      }),
    )
    .handler(async ({ context, input }) => {
      const userId = context.session.user.id;
      await validatePlanningScope({
        userId,
        yearId: input.yearId,
        subjectId: null,
      });
      const rows = await db
        .select()
        .from(timetableSeries)
        .where(
          and(
            eq(timetableSeries.userId, userId),
            eq(timetableSeries.yearId, input.yearId),
            input.includeMissing
              ? undefined
              : inArray(timetableSeries.syncState, ["managed", "detached"]),
          ),
        )
        .orderBy(
          asc(timetableSeries.startsOn),
          asc(timetableSeries.startMinutes),
        );
      const connections = await loadPlanningConnectionInfo(userId);
      return rows.map((row) => publicSeries(row, connections));
    }),

  listOccurrences: protectedProcedure
    .input(
      z.object({
        yearId: idSchema,
        includeMissing: z.boolean().default(false),
      }),
    )
    .handler(async ({ context, input }) => {
      const userId = context.session.user.id;
      await validatePlanningScope({
        userId,
        yearId: input.yearId,
        subjectId: null,
      });
      const rows = await db
        .select()
        .from(timetableOccurrences)
        .where(
          and(
            eq(timetableOccurrences.userId, userId),
            eq(timetableOccurrences.yearId, input.yearId),
            input.includeMissing
              ? undefined
              : inArray(timetableOccurrences.syncState, [
                  "managed",
                  "detached",
                ]),
          ),
        )
        .orderBy(asc(timetableOccurrences.startsAt));
      const connections = await loadPlanningConnectionInfo(userId);
      return rows.map((row) => publicOccurrence(row, connections));
    }),

  createSeries: protectedProcedure
    .input(createSeriesInput)
    .handler(async ({ context, input }) => {
      const userId = context.session.user.id;
      await validatePlanningScope({ userId, ...input });
      const [created] = await db
        .insert(timetableSeries)
        .values({
          title: input.title,
          notes: input.notes,
          localNote: input.localNote,
          startsOn: input.startsOn,
          endsOn: input.endsOn,
          startMinutes: input.startMinutes,
          durationMinutes: input.durationMinutes,
          timezone: input.timezone,
          recurrenceFrequency: input.recurrence.frequency,
          recurrenceInterval: input.recurrence.interval,
          recurrenceWeekdays: input.recurrence.weekdays as IsoWeekday[],
          location: input.location,
          subjectId: input.subjectId,
          yearId: input.yearId,
          userId,
          syncState: "detached",
        })
        .returning();
      return publicSeries(created!);
    }),

  updateSeries: protectedProcedure
    .input(updateSeriesInput)
    .handler(async ({ context, input }) => {
      const { seriesId, recurrence, ...patch } = input;
      const userId = context.session.user.id;
      const existing = await requireTimetableSeries(userId, seriesId);
      assertActive(existing, "Timetable series");
      assertEditablePatch("lesson", existing, {
        ...patch,
        ...(recurrence ? { recurrence } : {}),
        ...(patch.startsOn !== undefined || patch.startMinutes !== undefined
          ? { startsAt: true }
          : {}),
        ...(patch.endsOn !== undefined || patch.durationMinutes !== undefined
          ? { endsAt: true }
          : {}),
      });
      const startsOn = patch.startsOn ?? existing.startsOn;
      const endsOn =
        patch.endsOn === undefined ? existing.endsOn : patch.endsOn;
      if (endsOn && endsOn < startsOn) {
        badRequest("The timetable series cannot end before it starts");
      }
      const subjectId =
        patch.subjectId === undefined ? existing.subjectId : patch.subjectId;
      await validatePlanningScope({
        userId,
        yearId: existing.yearId,
        subjectId,
      });
      const [updated] = await db
        .update(timetableSeries)
        .set({
          ...patch,
          ...(recurrence
            ? {
                recurrenceFrequency: recurrence.frequency,
                recurrenceInterval: recurrence.interval,
                recurrenceWeekdays: recurrence.weekdays as IsoWeekday[],
              }
            : {}),
          updatedAt: new Date(),
        })
        .where(
          and(
            eq(timetableSeries.id, seriesId),
            eq(timetableSeries.userId, userId),
          ),
        )
        .returning();
      return publicSeries(updated!);
    }),

  deleteSeries: protectedProcedure
    .input(z.object({ seriesId: idSchema }))
    .handler(async ({ context, input }) => {
      const userId = context.session.user.id;
      const existing = await requireTimetableSeries(userId, input.seriesId);
      if (planningManagement("lesson", existing).mode === "provider") {
        badRequest(
          "Dismiss or detach a provider-managed series instead of deleting it",
        );
      }
      await db
        .delete(timetableSeries)
        .where(
          and(
            eq(timetableSeries.id, input.seriesId),
            eq(timetableSeries.userId, userId),
          ),
        );
      return { ok: true };
    }),

  dismissSeries: protectedProcedure
    .input(z.object({ seriesId: idSchema }))
    .handler(async ({ context, input }) => {
      const userId = context.session.user.id;
      const existing = await requireTimetableSeries(userId, input.seriesId);
      assertManaged(existing, "Timetable series");
      const [updated] = await db
        .update(timetableSeries)
        .set({ syncState: "dismissed", updatedAt: new Date() })
        .where(
          and(
            eq(timetableSeries.id, input.seriesId),
            eq(timetableSeries.userId, userId),
          ),
        )
        .returning();
      return publicSeries(updated!);
    }),

  detachSeries: protectedProcedure
    .input(z.object({ seriesId: idSchema }))
    .handler(async ({ context, input }) => {
      const userId = context.session.user.id;
      const existing = await requireTimetableSeries(userId, input.seriesId);
      assertManaged(existing, "Timetable series");
      const exceptions = await db
        .select()
        .from(timetableOccurrences)
        .where(
          and(
            eq(timetableOccurrences.userId, userId),
            eq(timetableOccurrences.seriesId, existing.id),
            inArray(timetableOccurrences.syncState, ["managed", "detached"]),
          ),
        );
      const now = new Date();
      const detached = await db.transaction(async (tx) => {
        const [created] = await tx
          .insert(timetableSeries)
          .values({
            title: existing.title,
            notes: existing.notes,
            localNote: existing.localNote,
            startsOn: existing.startsOn,
            endsOn: existing.endsOn,
            startMinutes: existing.startMinutes,
            durationMinutes: existing.durationMinutes,
            timezone: existing.timezone,
            recurrenceFrequency: existing.recurrenceFrequency,
            recurrenceInterval: existing.recurrenceInterval,
            recurrenceWeekdays: existing.recurrenceWeekdays,
            location: existing.location,
            subjectId: existing.subjectId,
            yearId: existing.yearId,
            userId,
            syncState: "detached",
          })
          .returning();
        if (exceptions.length > 0) {
          await tx.insert(timetableOccurrences).values(
            exceptions.map((row) => ({
              seriesId: created!.id,
              occurrenceDate: row.occurrenceDate,
              title: row.title,
              notes: row.notes,
              localNote: row.localNote,
              startsAt: row.startsAt,
              endsAt: row.endsAt,
              timezone: row.timezone,
              status: row.status,
              isException: row.isException,
              location: row.location,
              subjectId: row.subjectId,
              yearId: row.yearId,
              userId,
              syncState: "detached" as const,
            })),
          );
        }
        await tx
          .update(timetableSeries)
          .set({ syncState: "dismissed", updatedAt: now })
          .where(
            and(
              eq(timetableSeries.id, input.seriesId),
              eq(timetableSeries.userId, userId),
            ),
          );
        return created!;
      });
      return publicSeries(detached);
    }),

  createOccurrence: protectedProcedure
    .input(createOccurrenceInput)
    .handler(async ({ context, input }) => {
      const userId = context.session.user.id;
      if (input.seriesId === null) {
        await validatePlanningScope({ userId, ...input });
        if (input.endsAt <= input.startsAt) {
          badRequest("A timetable occurrence must end after it starts");
        }
        if (
          isoDateInTimeZone(input.startsAt, input.timezone) !==
          input.occurrenceDate
        ) {
          badRequest(
            "The occurrence date must match its start in the selected timezone",
          );
        }
        const [created] = await db
          .insert(timetableOccurrences)
          .values({ ...input, userId, syncState: "detached" })
          .returning();
        return publicOccurrence(created!);
      }

      const series = await requireTimetableSeries(userId, input.seriesId);
      assertActive(series, "Timetable series");
      const patch = {
        title: input.title,
        notes: input.notes,
        localNote: input.localNote,
        startsAt: input.startsAt,
        endsAt: input.endsAt,
        timezone: input.timezone,
        location: input.location,
        subjectId: input.subjectId,
      };
      assertEditablePatch("lesson", series, patch);
      const base = baseOccurrence(series, input.occurrenceDate);
      const values = {
        ...base,
        ...Object.fromEntries(
          Object.entries(patch).filter(([, value]) => value !== undefined),
        ),
      } as typeof base;
      if (values.endsAt <= values.startsAt) {
        badRequest("A timetable occurrence must end after it starts");
      }
      await validatePlanningScope({
        userId,
        yearId: series.yearId,
        subjectId: values.subjectId,
      });
      const [created] = await db
        .insert(timetableOccurrences)
        .values(values)
        .returning();
      return publicOccurrence(created!);
    }),

  updateOccurrence: protectedProcedure
    .input(updateOccurrenceInput)
    .handler(async ({ context, input }) => {
      const { occurrenceId, ...patch } = input;
      const userId = context.session.user.id;
      const existing = await requireTimetableOccurrence(userId, occurrenceId);
      assertActive(existing, "Timetable occurrence");
      assertEditablePatch("lesson", existing, patch);
      const startsAt = patch.startsAt ?? existing.startsAt;
      const endsAt = patch.endsAt ?? existing.endsAt;
      if (endsAt <= startsAt) {
        badRequest("A timetable occurrence must end after it starts");
      }
      const subjectId =
        patch.subjectId === undefined ? existing.subjectId : patch.subjectId;
      await validatePlanningScope({
        userId,
        yearId: existing.yearId,
        subjectId,
      });
      const [updated] = await db
        .update(timetableOccurrences)
        .set({ ...patch, isException: true, updatedAt: new Date() })
        .where(
          and(
            eq(timetableOccurrences.id, occurrenceId),
            eq(timetableOccurrences.userId, userId),
          ),
        )
        .returning();
      return publicOccurrence(updated!);
    }),

  cancelOccurrence: protectedProcedure
    .input(occurrenceLocator)
    .handler(async ({ context, input }) => {
      const userId = context.session.user.id;
      if ("seriesId" in input) {
        const series = await requireTimetableSeries(userId, input.seriesId);
        assertActive(series, "Timetable series");
        // Reject a provider-owned cancellation before materializing an exception.
        assertEditablePatch("lesson", series, { status: "cancelled" });
      }
      const existing = await resolveOrMaterialize(userId, input);
      assertActive(existing, "Timetable occurrence");
      assertEditablePatch("lesson", existing, { status: "cancelled" });
      const [updated] = await db
        .update(timetableOccurrences)
        .set({ status: "cancelled", isException: true, updatedAt: new Date() })
        .where(
          and(
            eq(timetableOccurrences.id, existing.id),
            eq(timetableOccurrences.userId, userId),
          ),
        )
        .returning();
      return publicOccurrence(updated!);
    }),

  deleteOccurrence: protectedProcedure
    .input(z.object({ occurrenceId: idSchema }))
    .handler(async ({ context, input }) => {
      const userId = context.session.user.id;
      const existing = await requireTimetableOccurrence(
        userId,
        input.occurrenceId,
      );
      if (planningManagement("lesson", existing).mode === "provider") {
        badRequest(
          "Dismiss or detach a provider-managed occurrence instead of deleting it",
        );
      }
      await db
        .delete(timetableOccurrences)
        .where(
          and(
            eq(timetableOccurrences.id, input.occurrenceId),
            eq(timetableOccurrences.userId, userId),
          ),
        );
      return { ok: true };
    }),

  dismissOccurrence: protectedProcedure
    .input(occurrenceLocator)
    .handler(async ({ context, input }) => {
      const userId = context.session.user.id;
      const existing = await resolveOrMaterialize(userId, input);
      assertManaged(existing, "Timetable occurrence");
      const [updated] = await db
        .update(timetableOccurrences)
        .set({
          syncState: "dismissed",
          isException: true,
          updatedAt: new Date(),
        })
        .where(
          and(
            eq(timetableOccurrences.id, existing.id),
            eq(timetableOccurrences.userId, userId),
          ),
        )
        .returning();
      return publicOccurrence(updated!);
    }),

  detachOccurrence: protectedProcedure
    .input(occurrenceLocator)
    .handler(async ({ context, input }) => {
      const userId = context.session.user.id;
      const existing = await resolveOrMaterialize(userId, input);
      assertManaged(existing, "Timetable occurrence");
      const now = new Date();
      const detached = await db.transaction(async (tx) => {
        const [created] = await tx
          .insert(timetableOccurrences)
          .values({
            seriesId: null,
            occurrenceDate: existing.occurrenceDate,
            title: existing.title,
            notes: existing.notes,
            localNote: existing.localNote,
            startsAt: existing.startsAt,
            endsAt: existing.endsAt,
            timezone: existing.timezone,
            status: existing.status,
            isException: false,
            location: existing.location,
            subjectId: existing.subjectId,
            yearId: existing.yearId,
            userId,
            syncState: "detached",
          })
          .returning();
        await tx
          .update(timetableOccurrences)
          .set({ syncState: "dismissed", isException: true, updatedAt: now })
          .where(
            and(
              eq(timetableOccurrences.id, existing.id),
              eq(timetableOccurrences.userId, userId),
            ),
          );
        return created!;
      });
      return publicOccurrence(detached);
    }),
};
