import type { ColorValue } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import {
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  Ban,
  Bell,
  BookMarked,
  Box,
  Calculator,
  Calendar,
  ChartLine,
  ChartNoAxesCombined,
  ChartNoAxesColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CirclePlus,
  CircleX,
  Clock,
  CloudOff,
  Copy,
  Crown,
  Eye,
  EyeOff,
  FileText,
  Flag,
  GraduationCap,
  Hourglass,
  House,
  Image,
  Layers,
  LayoutDashboard,
  Link,
  List,
  ListChecks,
  Lock,
  MailOpen,
  Megaphone,
  Minus,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Repeat,
  RotateCw,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Snowflake,
  Sparkles,
  Square,
  SquareCheck,
  Star,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Unlink,
  User,
  UserMinus,
  UserPlus,
  Users,
  UsersRound,
  Volume2,
  VolumeX,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react-native";

/**
 * The app's icons, drawn from the same set the web uses (Lucide), behind the
 * glyph-name API every screen already speaks. Swapping the table swapped the
 * whole app's iconography without touching a call site.
 *
 * The two OAuth logos stay on Ionicons: Lucide ships no brand marks.
 */
const MAP = {
  add: Plus,
  archive: Archive,
  "archive-outline": ArchiveRestore,
  "add-circle": CirclePlus,
  "albums-outline": Layers,
  "alert-circle": CircleAlert,
  "analytics-outline": ChartLine,
  "arrow-down-outline": ArrowDown,
  "arrow-forward": ArrowRight,
  "arrow-up-outline": ArrowUp,
  "ban-outline": Ban,
  "calculator-outline": Calculator,
  "calendar-outline": Calendar,
  "chart-combined": ChartNoAxesCombined,
  "book-marked": BookMarked,
  "layout-dashboard": LayoutDashboard,
  "list-checks": ListChecks,
  settings: Settings,
  shield: Shield,
  target: Target,
  checkbox: SquareCheck,
  checkmark: Check,
  "checkmark-circle": CircleCheck,
  "checkmark-circle-outline": CircleCheck,
  "chevron-back": ChevronLeft,
  "chevron-down": ChevronDown,
  "chevron-forward": ChevronRight,
  "chevron-up": ChevronUp,
  close: X,
  "close-circle": CircleX,
  "cloud-offline-outline": CloudOff,
  "copy-outline": Copy,
  crown: Crown,
  "cube-outline": Box,
  "document-text-outline": FileText,
  "eye-off-outline": EyeOff,
  "eye-outline": Eye,
  "flag-outline": Flag,
  flash: Zap,
  "help-circle-outline": CircleHelp,
  "home-outline": House,
  hourglass: Hourglass,
  "image-outline": Image,
  "layers-outline": Layers,
  "link-outline": Link,
  "list-outline": List,
  "lock-closed": Lock,
  "lock-closed-outline": Lock,
  "mail-open-outline": MailOpen,
  "megaphone-outline": Megaphone,
  "notifications-outline": Bell,
  "options-outline": SlidersHorizontal,
  pause: Pause,
  "pencil-outline": Pencil,
  "people-circle-outline": UsersRound,
  "people-outline": Users,
  "person-add-outline": UserPlus,
  "person-outline": User,
  "person-remove-outline": UserMinus,
  "phone-portrait-outline": Smartphone,
  play: Play,
  refresh: RefreshCw,
  "refresh-circle": RotateCw,
  remove: Minus,
  "remove-outline": Minus,
  repeat: Repeat,
  "school-outline": GraduationCap,
  "search-outline": Search,
  "shield-checkmark": ShieldCheck,
  "shield-checkmark-outline": ShieldCheck,
  "snow-outline": Snowflake,
  sparkles: Sparkles,
  "sparkles-outline": Sparkles,
  "square-outline": Square,
  star: Star,
  "stats-chart-outline": ChartNoAxesColumn,
  "time-outline": Clock,
  "trash-outline": Trash2,
  "trending-down": TrendingDown,
  "trending-down-outline": TrendingDown,
  "trending-up": TrendingUp,
  "trending-up-outline": TrendingUp,
  unlink: Unlink,
  "volume-medium": Volume2,
  "volume-mute": VolumeX,
  warning: TriangleAlert,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof MAP | "logo-google" | "logo-windows";

export function Icon({
  name,
  size = 18,
  color,
  strokeWidth = 2,
}: {
  name: IconName;
  size?: number;
  color?: ColorValue;
  strokeWidth?: number;
}) {
  if (name === "logo-google" || name === "logo-windows") {
    return <Ionicons name={name} size={size} color={color} />;
  }
  const Component = MAP[name] ?? CircleHelp;
  return (
    <Component size={size} color={color as string} strokeWidth={strokeWidth} />
  );
}
