import { z } from "zod";
import { nodeCapabilityIdSchema, type NodeCapabilityId } from "./node";

export const nodeCapabilityOperationSchema = z.enum([
  "conversation.provision",
  "conversation.append-event",
  "conversation.replay-events",
  "conversation.get-run",
  "conversation.export-owner",
  "conversation.delete-owner",
  "conversation.dag-create",
  "conversation.dag-list",
  "conversation.dag-get",
  "conversation.dag-append",
  "conversation.dag-branch",
  "conversation.dag-export",
  "conversation.dag-delete",
  "storage.capabilities",
  "storage.stat",
  "storage.get",
  "storage.get-range",
  "storage.put",
  "storage.delete",
  "storage.multipart-begin",
  "storage.multipart-part",
  "storage.multipart-complete",
  "storage.multipart-abort",
  "storage.copy",
  "storage.reconcile",
  "storage.authorize-transfer",
  "storage.execute-deletion-manifest",
  "lexical.capabilities",
  "lexical.upsert-version",
  "lexical.remove-version",
  "lexical.search",
  "lexical.get-chunks",
  "lexical.verify",
  "lexical.export-owner",
  "lexical.delete-owner",
  "retrieval.provider-fetch",
  "mcp.inspect",
  "mcp.invoke",
  "model.list",
  "model.stream",
  "model.embed",
  "model.transcribe",
  "model.estimate",
  "sandbox.capabilities",
  "sandbox.preflight",
  "sandbox.create",
  "sandbox.execute",
  "sandbox.put-files",
  "sandbox.get-files",
  "sandbox.read-file",
  "sandbox.snapshot-workspace",
  "sandbox.fork-workspace",
  "sandbox.stop",
  "sandbox.destroy",
  "sandbox.runtime-checkpoint-capabilities",
  "sandbox.capture-runtime-checkpoint",
  "sandbox.restore-runtime-checkpoint",
  "sandbox.delete-runtime-checkpoint",
]);
export type NodeCapabilityOperation = z.infer<
  typeof nodeCapabilityOperationSchema
>;

export const nodeOperationPayloadSchema = z.strictObject({
  ownerId: z.string().min(1).max(256),
  input: z.unknown(),
});
export type NodeOperationPayload = z.infer<typeof nodeOperationPayloadSchema>;

export const nodeWireBytesSchema = z.strictObject({
  encoding: z.literal("base64url"),
  byteLength: z
    .number()
    .int()
    .nonnegative()
    .max(64 * 1024 * 1024),
  data: z.string().max(96 * 1024 * 1024),
});
export type NodeWireBytes = z.infer<typeof nodeWireBytesSchema>;

const operationCapabilities: Record<NodeCapabilityOperation, NodeCapabilityId> =
  {
    "conversation.provision": "conversations",
    "conversation.append-event": "conversations",
    "conversation.replay-events": "conversations",
    "conversation.get-run": "conversations",
    "conversation.export-owner": "conversations",
    "conversation.delete-owner": "conversations",
    "conversation.dag-create": "conversations",
    "conversation.dag-list": "conversations",
    "conversation.dag-get": "conversations",
    "conversation.dag-append": "conversations",
    "conversation.dag-branch": "conversations",
    "conversation.dag-export": "conversations",
    "conversation.dag-delete": "conversations",
    "storage.capabilities": "storage",
    "storage.stat": "storage",
    "storage.get": "storage",
    "storage.get-range": "storage",
    "storage.put": "storage",
    "storage.delete": "storage",
    "storage.multipart-begin": "storage",
    "storage.multipart-part": "storage",
    "storage.multipart-complete": "storage",
    "storage.multipart-abort": "storage",
    "storage.copy": "storage",
    "storage.reconcile": "storage",
    "storage.authorize-transfer": "storage",
    "storage.execute-deletion-manifest": "storage",
    "lexical.capabilities": "retrieval",
    "lexical.upsert-version": "retrieval",
    "lexical.remove-version": "retrieval",
    "lexical.search": "retrieval",
    "lexical.get-chunks": "retrieval",
    "lexical.verify": "retrieval",
    "lexical.export-owner": "retrieval",
    "lexical.delete-owner": "retrieval",
    "retrieval.provider-fetch": "retrieval",
    "mcp.inspect": "mcp",
    "mcp.invoke": "mcp",
    "model.list": "models",
    "model.stream": "models",
    "model.embed": "models",
    "model.transcribe": "models",
    "model.estimate": "models",
    "sandbox.capabilities": "sandbox",
    "sandbox.preflight": "sandbox",
    "sandbox.create": "sandbox",
    "sandbox.execute": "sandbox",
    "sandbox.put-files": "sandbox",
    "sandbox.get-files": "sandbox",
    "sandbox.read-file": "sandbox",
    "sandbox.snapshot-workspace": "sandbox",
    "sandbox.fork-workspace": "sandbox",
    "sandbox.stop": "sandbox",
    "sandbox.destroy": "sandbox",
    "sandbox.runtime-checkpoint-capabilities": "sandbox",
    "sandbox.capture-runtime-checkpoint": "sandbox",
    "sandbox.restore-runtime-checkpoint": "sandbox",
    "sandbox.delete-runtime-checkpoint": "sandbox",
  };

export function nodeOperationCapability(operation: NodeCapabilityOperation) {
  return nodeCapabilityIdSchema.parse(operationCapabilities[operation]);
}
