name: 🐋 Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push API Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: nayzbysodium/avermate-api:latest

      - name: Build and Push Web Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/client/Dockerfile
          push: true
          tags: nayzbysodium/avermate-web:latest
          build-args: |
            NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
            NEXT_PUBLIC_CLIENT_URL=$NEXT_PUBLIC_CLIENT_URL
        env:
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_CLIENT_URL: ${{ vars.NEXT_PUBLIC_CLIENT_URL }}
